### ISSUE TITLE
Allow Realm or custom context in DataProtection

### ISSUE THREAD

**Issue by agrothe** [coronabytes/ArangoDB#1]
I'd like to use a different connection string for the `SeriLog` and `DataProtection` than for the rest of my application. Right now, `DataProtection` currently gets the `ArangoContext` based on injection which means I have to subclass `ArangoContext` to use in the rest of my application.

It would be nice if:

`dataProtection.PersistKeysToArangoDB(database: "dataprotection", collection: "keys");`

took a an optional realm, connection string, or instance.

**Comment by agrothe** [comment]
Thanks for this. I also created an interface for ArangoContext in case you would like to add that. Helps in unit testing. Unless you have other suggestions. https://gist.github.com/agrothe/f4e196ff52b7eb4138b31bc82c7b3223

**Comment by coronabytes** [comment]
Yeah thanks, I will extract an interface for the context.
However for our projects/products we just run tests against a real arango instance.

Is there anything else you''ll need from the driver? Just collection ideas

**Comment by agrothe** [comment]
So far its great. I didn't have the time to finish the one I started and this is exactly what I need for a multi-tenant app. Looking forward to an implementation of velocystream. Attempted a few times but the documentation is fairly limited. 

I started a multi-tenant howto series which I'm going to try and finish after I update it to Core 3.1. Planning on adding in this driver so that should help with some documentation. https://dev.to/agrothe/multi-tenant-applications-with-asp-net-core-2-2-getting-started-16n3 

I'll ping back once it's done. Also I could probably help out with some documentation if you get something started.

**Comment by coronabytes** [comment]
Yeah velocysteam and its lack of documentation...
Please just vote on the following issue [https://github.com/arangodb/arangodb/issues/11499#issue-606766822](https://github.com/arangodb/arangodb/issues/11499#issue-606766822)
It will solve almost everything including writing this "core" driver

**Comment by agrothe** [comment]
I did already. There is where I found this. I've added a comment as well.
