### ISSUE TITLE
AsQueryable missing from NuGet latest

### ISSUE THREAD

**Issue by agrothe** [coronabytes/ArangoDB#2]
The Linq extension is missing from the latest NuGet package. Is this ready to be published or should I build from source for now?

**Comment by coronabytes** [comment]
Nope it's far from release ready - you can compile it yourself and see how far you'll come.
It's a students master thesis by the way

**Comment by agrothe** [comment]
Ok, thanks. Is there any plans to maintain the repository after the thesis? I like the simplicity.

**Comment by coronabytes** [comment]
Ah only refering to the LINQ mod.
All except the LINQ module is part of two commercial products. So we kinda have to maintain the driver.

 I will swap the 'core' if an official driver with the same features ever comes to light.

**Comment by agrothe** [comment]
Sounds good. Thanks.
